-
  name: Test Connectivity
  hosts: web_server
  vars:
    #ansible_ssh_pass: "{{ lookup('ini', 'password section=web_server file=credentials.ini') }}"
    #ansible_ssh_pass: "{{ lookup('ini', 'password', section='web_server', file='credentials.ini') }}"
    ansible_ssh_pass: {{ lookup('ini', 'web_server.password', file='credentials.ini') }}
  tasks:
  - name: Ping target host
    ping:
           data: "Test"
